CraftMaps/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('theCraftMapsCO.urls')),
    url(r'^home/', include('theCraftMapsCO.urls')),
    url(r'^routes/', include('theCraftMapsCO.urls')),
    url(r'^about/', include('theCraftMapsCO.urls')),
    url(r'^contact/', include('theCraftMapsCO.urls')),
    url(r'^multiRoutes/', include('theCraftMapsCO.urls')),
    url(r'^brewery/', include('theCraftMapsCO.urls')),
    url(r'^signup/', include('theCraftMapsCO.urls')),
    url(r'^login/', include('theCraftMapsCO.urls')),
    url(r'^logout/', include('theCraftMapsCO.urls')),
    url(r'^user/', include('theCraftMapsCO.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

command_project/command_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

theCraftMapsCO/urls.py
from django.conf.urls import url
from theCraftMapsCO import views
from django.contrib.auth import views as auth_views
from .forms import CustomAuthForm

urlpatterns = [
    url(r'^$', views.home, name='homepage'),
    url(r'^home/$', views.home, name='homepage'),
    url(r'^routes/$', views.routes, name='routes'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^multiRoutes/$', views.multiRoutes, name='multiRoutes'),
    url(r'^brewery/(?P<name>.*)/$', views.brewery_page, name='brewery_page'),
    url(r'^login/$', auth_views.login, name='login',
        kwargs={"authentication_form": CustomAuthForm, 'template_name': 'login.html'}),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^user/$', views.user_page, name='user_page')
]

#url(r'^routes/(?P<start>\w+)/$', views.routes, name='routes')

theCraftMapsCO/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Brewery_Table(models.Model):
    Brewery_Name = models.CharField(max_length=90)
    Brewery_Region = models.CharField(max_length=90, default='Dublin')
    Brewery_Address = models.CharField(max_length=500, default='Dublin, Ireland')
    Brewery_Type = models.CharField(max_length=50, default='Brewery')
    Brewery_Rating = models.DecimalField(max_digits=4, decimal_places=2, default=2.5)
    Brewery_Latitude = models.DecimalField(max_digits=13, decimal_places=10)
    Brewery_Longitude = models.DecimalField(max_digits=13, decimal_places=10)
    Brewery_URL = models.URLField(max_length=255, null=True, blank=True)
    Brewery_Twitter = models.URLField(max_length=255, null=True, blank=True)
    Brewery_Facebook = models.URLField(max_length=255, null=True, blank=True)
    Brewery_Tours = models.BooleanField(default=False)
    Brewery_Merch = models.BooleanField(default=False)

    def _str_(self):
        return self.Brewery_Name


class Beer_Table(models.Model):
    Beer_Name = models.CharField(max_length=155)
    Beer_Brewery = models.CharField(max_length=155)
    Beer_Type = models.CharField(max_length=90)
    Beer_Percent = models.DecimalField(max_digits=4, decimal_places=2)
    Beer_Rating = models.DecimalField(max_digits=4, decimal_places=2)

    def _str_(self):
        return self.Beer_Name


class User_Table(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    User_Favorite_Brewery_Type = models.CharField(max_length=90)
    User_Max_Distance = models.IntegerField(default=20)
    User_Beer_Stout = models.BooleanField(default=False)
    User_Beer_Lager = models.BooleanField(default=False)
    User_Beer_IPA = models.BooleanField(default=False)
    User_Beer_Cider = models.BooleanField(default=False)
    User_Beer_Pilsner = models.BooleanField(default=False)
    User_Beer_Ale = models.BooleanField(default=False)
    User_Beer_Weiss = models.BooleanField(default=False)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        User_Table.objects.create(user=instance)

class User_Brewery_Ratings(models.Model):
    Brewery_Id = models.IntegerField()
    User_Id = models.IntegerField()
    User_Brewery_Rating = models.DecimalField(max_digits=4, decimal_places=2)
    Rating_Time_Stamp = models.DateField(blank=True)
    User_Do_Tour = models.BooleanField(default=False)
    User_Drink_Beer = models.BooleanField(default=False)
    User_Buy_Merch = models.BooleanField(default=False)

theCraftMapsCO/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from .forms import SignUpForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from .models import User_Table, Beer_Table, Brewery_Table, User
from datetime import datetime
from math import sin, cos, sqrt, atan2, radians
from random import randint
import googlemaps
import simplejson
import pandas as pd
import operator
import difflib
import twitter


# Support Methods
googleKey = "AIzaSyDFK8QRiUl8jx5YYQwDMQ31GMyXwXz-et8"
gmaps = googlemaps.Client(key=googleKey)


# Twitter API info
consumer_key = '16iWxCzBIzdwaRusHVnUdYxLs'
consumer_secret = 'Q677oYS73EP4UFBgJfRnG1npGTfcgd1B9xbpaxBQxocxawCW5T'
access_token_key = '959052235815649280-GxbCZphkg4oUizZ4QeUwyksToEFaIiB'
access_token_secret = 'NY41FPXbM1NLmhlwXircyArfSXHUTvZqBRK668BTSVTMU'


# Create your views here.
###########################################################
# Home Page
def home(request):
    context = {
        'brewery': Brewery_Table.objects.get(id=1),
        'brewery_json': build_home_json(Brewery_Table.objects.all()),
        'key': googleKey
    }
    return render(request, 'homepage.html', context)


# builds json for map
def build_home_json(data):
    rtn_json = []
    for d in data:
        item = {
            'name': d.Brewery_Name,
            'coords': {
                'lng': float(d.Brewery_Longitude),
                'lat': float(d.Brewery_Latitude)
            },
            'Content': '<div id="iw-container" class="infoDiv"><div class="infoHeader iw-title"><label class="headerLabel">'+d.Brewery_Name+'</label></div><div class="infoBody iw-content"><label class="bodyLabel">'+d.Brewery_Type+'</label></div></div>'
        }
        rtn_json.append(item)
    return simplejson.dumps(rtn_json, separators=(',', ':'))


################################################################
# builds single route
def routes(request):
    # number of breweries displayed
    k_size = 10
    # content fix for Kush
    bool = False
    # post request
    if request.method == 'POST':
        data_saving_method(str(request.POST.get('value1')) + "," + str(request.POST.get('value2')))
        lat = request.POST.get('value1')
        lng = request.POST.get('value2')
        starting_point = (float(lat), float(lng))
    # else get
    elif request.method == 'GET':
        start = read_data('data_dump.txt')
        start = start.split(",")
        starting_point = (float(start[0]), float(start[1]))
    # else
    else:
        starting_point = (53.3256826, -6.2249631)
    context = {
        'locations': builddistjson(request, Brewery_Table.objects.all(), starting_point, k_size, bool),
        'start': list(starting_point),
        'key': googleKey
    }
    return render(request, 'routes.html', context)


# builds multi route
def multiRoutes(request):
    # number of breweries displayed
    k_size = 10
    # content fix for Kush
    bool = True
    # post request
    if request.method == 'POST':
        data_saving_method(str(request.POST.get('value1')) + "," + str(request.POST.get('value2')))
        lat = request.POST.get('value1')
        lng = request.POST.get('value2')
        starting_point = (float(lat), float(lng))
    elif request.method == 'GET':
        start = read_data('data_dump.txt')
        start = start.split(",")
        starting_point = (float(start[0]), float(start[1]))
    else:
        starting_point = (53.3256826, -6.2249631)
    context = {
        'locations': builddistjson(request, Brewery_Table.objects.all(), starting_point, k_size, bool),
        'start': list(starting_point),
        'key': googleKey
    }
    return render(request, 'multiRoutes.html', context)


# builds json for page
def builddistjson(request, breweries, starting, k, is_multi):
    # user defined
    if request.user.is_authenticated:
        #user_data = User_Table.objects.get(id=request.user.id)
        #distance_cutoff = user_data.User_Max_Distance
        distance_cutoff = 10.0
    # default
    else:
        distance_cutoff = 15.0
    data = []
    for dat in breweries:
        nam = dat.Brewery_Name
        typ = dat.Brewery_Type
        rat = dat.Brewery_Rating
        dst = get_distance(starting, (dat.Brewery_Longitude, dat.Brewery_Latitude))
        # builds on distance
        if dst < distance_cutoff:
            # data
            data.append(
                {
                    'Name': nam,
                    'Type': typ,
                    'Rating': rat,
                    'Distance': dst
                }
            )
    # sort based on distance
    df = sorted(data, key=operator.itemgetter('Distance'))
    # filters based on user preference
    ndf = similarity_map(request, df, (k+k))
    # subset of data
    subset = []
    for d in ndf[:k]:
        subset.append(d['Name'])
    rtn_json = []

    for d in breweries:
        if d.Brewery_Name in subset:
            # if multi trip, remove button
            if is_multi:
                content_str = '<div id="iw-container" class="infoDiv"><div class="infoHeader iw-title"><label class="headerLabel" id = "' + d.Brewery_Name + '" onClick="showModal(event);">' + d.Brewery_Name + '</label></div><div class="infoBody iw-content"><label class="bodyLabel">' + d.Brewery_Type + '</label></div></div>'
            else:
                content_str = '<div id="iw-container" class="infoDiv"><div class="infoHeader iw-title"><label class="headerLabel" id = "' + d.Brewery_Name + '" onClick="showModal(event);">' + d.Brewery_Name + '</label></div><div class="infoBody iw-content"><label class="bodyLabel">' + d.Brewery_Type + '</label></div><div class="infoFooter iw-bottom-gradient"><button class="viewButton btn btn-outline" onClick="getDirections(' + str(d.Brewery_Latitude) + ',' + str(d.Brewery_Longitude) + ');">See my Directions</button></div></div>'

            item = {
                'name': d.Brewery_Name,
                'coords': {
                    'lng': float(d.Brewery_Longitude),
                    'lat': float(d.Brewery_Latitude)
                },
                'Content': content_str            }
            rtn_json.append(item)
    # returns json
    return simplejson.dumps(rtn_json, separators=(',', ':'))


# classifies based on users preferred brewery type
def similarity_map(request, data, k):
    data_map = []
    # users favourite brewery type
    if request.user.is_authenticated:
        user_data = User_Table.objects.get(id=request.user.id)
        user_brewery = user_data.User_Favorite_Brewery_Type
        types_of_brewery = ["BrewPub", "Microbrewery", "Commercial Brewery", "Client Brewery", str(user_brewery)]
    # else uses generic list
    else:
        types_of_brewery = ["BrewPub", "Microbrewery", "Commercial Brewery", "Client Brewery"]
    # builds a similarity map based on user preference
    for item in data[:k]:
        # random selection of brewery
        rand = randint(0, len(types_of_brewery)-1)
        check = types_of_brewery[rand]
        # gets similarity
        similarity_result = difflib.SequenceMatcher(None, check, item['Type']).ratio()
        # finds best similarity
        data_map.append(
            {
                'Name': item['Name'],
                'Type': item['Type'],
                'Distance': item['Distance'],
                'Rating': float(item['Rating']),
                'Sim': similarity_result
             }
        )
    # sorts on distance in ASC, then by sim and rating in DESC
    data_map = sorted(data_map, reverse=False, key=operator.itemgetter('Distance'))
    rtn = sorted(data_map, reverse=True, key=operator.itemgetter('Sim', 'Rating'))
    dump_test(rtn)
    # returns data
    return rtn


# Clean distance API response
def get_distance(start, finish):
    try:
        if not isinstance(start, tuple):
            geocode_result = gmaps.geocode(start[0], start[1])
        else:
            geocode_result = (start[0], start[1])
        # approximate radius of earth in km
        R = 6373.1
        lat1 = radians(geocode_result[0])
        lon1 = radians(geocode_result[1])
        lon2 = radians(float(finish[0]))
        lat2 = radians(float(finish[1]))
        dlon = lon2 - lon1
        dlat = lat2 - lat1
        a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
        c = 2 * atan2(sqrt(a), sqrt(1 - a))
        distance = R * c
    except googlemaps.exceptions.ApiError as err:
        print(err)
    return distance


#########################################################
# about page
def about(request):
    context = {
    }
    return render(request, 'about.html', context)


#########################################################
# contacts page
def contact(request):
    context = {
    }
    return render(request, 'contact.html', context)


######################################################################
# data logging methods
def data_saving_method(test_data):
    with open("data_dump.txt", "w") as text_file:
        text_file.write(test_data)
        text_file.close()


# reads file
def read_data(file):
    with open(file, 'r') as text_file:
        data = text_file.read()
        text_file.close()
        return data


# log file for testing
def dump_test(test_data):
    with open("log_dump.txt", "w") as text_file:
        text_file.write(str(test_data))
        text_file.close()


#########################################################
#Build JSON for Brewery Page
def buildBreweryJson(data):
    rtn_json = []
    item = {
        'name': data.Brewery_Name,
        'coords': {
            'lng': float(data.Brewery_Longitude),
            'lat': float(data.Brewery_Latitude)
        },
        'address': {
            'name': data.Brewery_Name,
            'location': data.Brewery_Address,
            'region': data.Brewery_Region
        },
        'brewery_type': data.Brewery_Type,
        'rating': data.Brewery_Rating,
        'social': {

theCraftMapsCO/templates/theCraftMapsCO/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Craft Maps:About</title>

    {% load static %}

    <!--JS files -->
    <script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
    <script src='{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}'></script>
    <script src='{% static "vendor/jquery-easing/jquery.easing.min.js" %}'></script>
	
    <link rel="stylesheet" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'/>

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}'/>
    <link rel="stylesheet" href='{% static "vendor/simple-line-icons/css/simple-line-icons.css" %}'/>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
	<!-- Custom styles for this template -->
    <link rel="stylesheet" href='{% static "css/full-width-pics.css" %}'>

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href='{% static "css/new-age.min.css" %}'/>
    <link rel="stylesheet" href='{% static "css/about.css" %}'/>
</head>

<body id="page-top">

	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
		<div class="container">
			<img src='{% static "img/Screen Shot 2018-08-02 at 19.08.05 1.png" %}' width="40px" height="40px" />
				<a class="navbar-brand js-scroll-trigger" href="/home"><img src='{% static "img/Screen Shot 2018-08-02 at 19.07.45.png" %}' width="140px" height="30px" /></a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
					data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
					aria-label="Toggle navigation">
				Menu
				<i class="fa fa-bars"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a class="nav-link" href="/home">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="/about">About</a>
					</li>
					<li class="nav-item">
						<a class="nav-link js-scroll-trigger" href="/contact">Contact</a>
					</li>
					<li class="nav-item">
						{% if user.is_authenticated %}
							<a class="nav-link" href="/logout">Logout</a>
						{% else %}
							<a class="nav-link" href="/login">Login</a>
						{% endif %}
					</li>
				</ul>
			</div>
		</div>
	</nav>

	<!-- Header - set the background image for the header in the line below -->
	<section class="py-5 bg-image-full" style="background-image: url('../static/img/309fca98e74e4c50a735e3c0bd6987de.gif');">
		<!-- Put anything you want here! There is just a spacer below for demo purposes! -->
		<div style="height: 200px;"></div>
	</section>

	<!-- Content section -->
    <section style="background-image: url('../static/img/home background 1.png');" class="py-5 backgroundSection">
      <div class="container">
        <h1>About Us</h1> 
		<p class="lead">What are we offering?</p>
        <p>Craft Maps gives you the opportunity to explore craft beer in Ireland showing you the top breweries, microbreweries and brewpubs to choose from. Select your brewery trip (Single trip/multi-trip) and we organise it for you. Get ready for the Craft Maps experience!</p>
      </div>
    </section>

	<footer>
		<div class="container">
			<p>&copy; Craft Maps 2018</p>
			<ul class="list-inline">
				<li class="list-inline-item">
					<a href="#">Privacy</a>
				</li>
				<li class="list-inline-item">
					<a href="#">Terms</a>
				</li>
				<li class="list-inline-item">
					<a href="#">FAQ</a>
				</li><a id="safetyLink" href="https://www.drinkaware.ie" target="_blank"><img src='{% static "img/Drinkaware.png" %}' /></a>
			</ul>
			<ul class="list-inline">
				<li class="list-inline-item">
					<a href="https://twitter.com/theCraftMaps1" target="_blank"><i class="fa fa-twitter"></i></a>
				</li>
				<li class="list-inline-item">
					<a href="https://www.facebook.com/thecraft.mapsco.1" target="_blank"><i class="fa fa-facebook"></i></a>
				</li>
				<li class="list-inline-item">
					<a href="https://www.instagram.com/thecraftmapsco/" target="_blank"><i class="fa fa-instagram"></i></a>
				</li>
			</ul>
		</div>
	</footer>
	<script src='{% static "js/new-age.min.js" %}'></script>
</body>
</html>

theCraftMapsCO/templates/theCraftMapsCO/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Craft Maps: Sign Up</title>
	{% load static %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" src='{% static "img/favicon.ico" %}'/>
	<link rel="stylesheet" href='{% static "vendor/bootstrap/css/bootstrap.min.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/font-awesome/css/font-awesome.min.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/font-awesome/css/icon-font.min.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/bootstrap/css/animate.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/bootstrap/css/hamburgers.min.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/bootstrap/css/select2.min.css" %}'/>
	<link rel="stylesheet" href='{% static "vendor/bootstrap/css/util.css" %}'/>
	<link rel="stylesheet" href='{% static "css/signup.css" %}'/>
</head>
<body>
{% block content %}
	<div class="limiter">
		 <div id="backgroundContainer" class="container-login100" style="background-image: url('../static/img/WhatsApp Image 2018-07-28 at 15.30.48.jpeg');">
			<div class="wrap-login100 p-t-310 p-b-30">
				<form class="login100-form validate-form" method="post">
				{% csrf_token %}
					<div class="login100-form-avatar">
						<a href="../home"><img src="../static/img/cm-logo-01.png"></a>
					</div>

					<span class="login100-form-title p-t-20 p-b-45">
						Sign Up
					</span>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ sign_up_form.username}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ sign_up_form.first_name}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ sign_up_form.last_name}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ sign_up_form.email}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input m-b-10" data-validate = "Password is required">
						{{ sign_up_form.password1}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Password is required">
						{{ sign_up_form.password2}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
					</div>
					
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ user_form.User_Favorite_Brewery_Type}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10" data-validate = "Username is required">
						{{ user_form.User_Max_Distance}}
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Stout:</label>
						{{ user_form.User_Beer_Stout}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Lager:</label>
						{{ user_form.User_Beer_Lager}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">IPA:</label>
						{{ user_form.User_Beer_IPA}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Cider:</label>
						{{ user_form.User_Beer_Cider}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Pilsner:</label>
						{{ user_form.User_Beer_Pilsner}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Ale:</label>
						{{ user_form.User_Beer_Ale}}
					</div>
					<div class="wrap-input100 validate-input m-b-10 form-group login-group-checkbox" data-validate = "Username is required">
						<label for="id_User_Beer_Stout">Weiss:</label>
						{{ user_form.User_Beer_Weiss}}
					</div>

					<div class="container-login100-form-btn p-t-10">
						<button type="submit" class="login100-form-btn">
							Sign Up
						</button>
					</div>
{% endblock %}
					<div class="text-center w-full p-t-25 p-b-230">
						<a href="../login" class="txt1">
							Already have an account? Login!
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src='{% static "js/jquery-3.3.1.min.js" %}'></script>
	<script src='{% static "vendor/bootstrap/js/popper.js" %}'></script>
	<script src='{% static "vendor/bootstrap/js/bootstrap.min.js" %}'></script>
	<script src='{% static "vendor/bootstrap/js/select2.min.js" %}'></script>

</body>
</html>